<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FunkinSharp.Resources\FunkinSharp.Resources.csproj" />
    <ProjectReference Include="..\FunkinSharp.API\FunkinSharp.API.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ppy.osu.Framework" Version="2026.807.0" />
  </ItemGroup>
</Project>
