<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Fonts\**\*" />
    <EmbeddedResource Include="Samples\**\*" />
    <EmbeddedResource Include="Textures\**\*" />
    <EmbeddedResource Include="ResourcePacks\**\*" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="ResourcePacks\vanilla\stages\" />
    <Folder Include="ResourcePacks\week1\songs\" />
  </ItemGroup>
</Project>
